import { Prisma } from '@prisma/client';

export const taskCategories: Prisma.TaskCategoryCreateInput[] = [
  {
    name: 'academic_affairs',
    nameKo: '교무학사',
    description: '수업, 평가, 학적 관련 업무',
    icon: 'book-open',
    color: '#3B82F6',
    order: 1,
  },
  {
    name: 'student_guidance',
    nameKo: '학생생활',
    description: '생활지도, 상담, 안전교육 관련 업무',
    icon: 'users',
    color: '#10B981',
    order: 2,
  },
  {
    name: 'school_events',
    nameKo: '학교행사',
    description: '입학식, 졸업식, 체육대회 등 학교 행사',
    icon: 'calendar',
    color: '#F59E0B',
    order: 3,
  },
  {
    name: 'administrative',
    nameKo: '행정업무',
    description: '문서작성, 보고, 예산 관련 업무',
    icon: 'file-text',
    color: '#8B5CF6',
    order: 4,
  },
  {
    name: 'curriculum',
    nameKo: '교육과정',
    description: '교육과정 편성 및 운영 관련 업무',
    icon: 'layout-grid',
    color: '#EC4899',
    order: 5,
  },
  {
    name: 'special_education',
    nameKo: '특수교육',
    description: '특수교육대상자 지원 관련 업무',
    icon: 'heart',
    color: '#14B8A6',
    order: 6,
  },
  {
    name: 'school_meals',
    nameKo: '급식',
    description: '급식 운영 및 식생활 교육',
    icon: 'utensils',
    color: '#F97316',
    order: 7,
  },
  {
    name: 'facilities',
    nameKo: '시설관리',
    description: '학교시설 및 환경 관리',
    icon: 'building',
    color: '#6366F1',
    order: 8,
  },
  {
    name: 'ict',
    nameKo: '정보화',
    description: 'ICT 활용 교육 및 정보화 업무',
    icon: 'laptop',
    color: '#0EA5E9',
    order: 9,
  },
  {
    name: 'safety',
    nameKo: '안전',
    description: '학교안전, 재난대비, 보건 관련',
    icon: 'shield',
    color: '#EF4444',
    order: 10,
  },
  {
    name: 'after_school',
    nameKo: '방과후학교',
    description: '방과후학교 및 돌봄 관련 업무',
    icon: 'clock',
    color: '#84CC16',
    order: 11,
  },
  {
    name: 'parent_community',
    nameKo: '학부모/지역사회',
    description: '학부모 상담, 지역사회 연계 업무',
    icon: 'home',
    color: '#A855F7',
    order: 12,
  },
];
