import { Prisma, Priority, RecurringType } from '@prisma/client';

interface TaskSeed {
  title: string;
  description: string;
  categoryName: string;
  month?: number;
  startMonth?: number;
  endMonth?: number;
  isRecurring?: boolean;
  recurringType?: RecurringType;
  priority: Priority;
  estimatedHours?: number;
  targetGrades: number[];
  targetPositions: string[];
  source?: string;
  tags: string[];
  workflowSteps?: WorkflowStepSeed[];
}

interface WorkflowStepSeed {
  order: number;
  title: string;
  description?: string;
  checkItems?: { id: string; text: string; isOptional?: boolean }[];
  tips?: string[];
  warnings?: string[];
  estimatedTime?: number;
}

export const tasks: TaskSeed[] = [
  // ===========================================
  // 3월 업무
  // ===========================================
  {
    title: '학급 편성 및 담임 배정',
    description: '새 학년도 학급 편성과 담임교사 배정 업무',
    categoryName: 'academic_affairs',
    month: 3,
    priority: 'URGENT',
    estimatedHours: 8,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['교감', '교무부장'],
    source: '전국 1000+ 학교 공통',
    tags: ['학급편성', '담임배정', '학년초'],
    workflowSteps: [
      {
        order: 1,
        title: '전년도 학급 현황 분석',
        description: '전년도 학급 구성 및 특이사항 파악',
        checkItems: [
          { id: '1', text: '전년도 학급별 학생 수 확인' },
          { id: '2', text: '특수교육대상자 현황 파악' },
          { id: '3', text: '다문화학생 현황 파악' },
          { id: '4', text: '학생 간 관계(갈등/친분) 정보 수집' },
        ],
        tips: ['전년도 담임교사 의견을 반드시 수렴하세요'],
        estimatedTime: 60,
      },
      {
        order: 2,
        title: '학급 편성 기준 수립',
        description: '공정하고 균형잡힌 학급 편성 기준 마련',
        checkItems: [
          { id: '1', text: '남녀 성비 균형' },
          { id: '2', text: '학력 수준 균형' },
          { id: '3', text: '특수교육대상자 배치' },
          { id: '4', text: '쌍둥이/형제 분리 여부 결정' },
        ],
        estimatedTime: 30,
      },
      {
        order: 3,
        title: '학급 편성안 작성',
        description: 'NEIS를 활용한 학급 편성',
        checkItems: [
          { id: '1', text: 'NEIS 학급편성 메뉴 접속' },
          { id: '2', text: '학급별 학생 배치' },
          { id: '3', text: '편성 결과 검토' },
          { id: '4', text: '관리자 결재' },
        ],
        warnings: ['편성 확정 전 반드시 특수교육대상자 배치를 재확인하세요'],
        estimatedTime: 120,
      },
      {
        order: 4,
        title: '담임교사 배정',
        description: '교사 희망 및 적성을 고려한 담임 배정',
        checkItems: [
          { id: '1', text: '교사 담임 희망 학년 조사' },
          { id: '2', text: '담임 배정안 작성' },
          { id: '3', text: '교장 승인' },
          { id: '4', text: '담임 발표' },
        ],
        tips: ['연속 담임 여부, 특수학급 담당 경력 등을 고려하세요'],
        estimatedTime: 60,
      },
    ],
  },
  {
    title: '입학식 준비 및 진행',
    description: '신입생 입학식 행사 준비 및 진행',
    categoryName: 'school_events',
    month: 3,
    priority: 'URGENT',
    estimatedHours: 16,
    targetGrades: [1],
    targetPositions: ['교무부장', '1학년부장', '담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['입학식', '신입생', '학교행사'],
    workflowSteps: [
      {
        order: 1,
        title: '입학식 기본 계획 수립',
        description: '일시, 장소, 식순 등 기본 계획 수립',
        checkItems: [
          { id: '1', text: '입학식 일시 확정' },
          { id: '2', text: '행사 장소 확정 (강당/운동장)' },
          { id: '3', text: '식순 작성' },
          { id: '4', text: '역할 분담표 작성' },
        ],
        estimatedTime: 60,
      },
      {
        order: 2,
        title: '입학식 준비물 점검',
        description: '행사에 필요한 물품 및 시설 점검',
        checkItems: [
          { id: '1', text: '현수막 제작 의뢰' },
          { id: '2', text: '방명록 준비' },
          { id: '3', text: '화환 수령 계획' },
          { id: '4', text: '음향/영상 장비 점검' },
          { id: '5', text: '의자 배치 계획' },
        ],
        estimatedTime: 120,
      },
      {
        order: 3,
        title: '입학 안내문 발송',
        description: '학부모 대상 입학 안내문 작성 및 발송',
        checkItems: [
          { id: '1', text: '안내문 작성' },
          { id: '2', text: '관리자 결재' },
          { id: '3', text: '가정통신문 발송' },
          { id: '4', text: '학교 홈페이지 게시' },
        ],
        estimatedTime: 60,
      },
      {
        order: 4,
        title: '리허설 및 최종 점검',
        description: '입학식 전날 최종 점검',
        checkItems: [
          { id: '1', text: '식순 리허설' },
          { id: '2', text: '음향/영상 테스트' },
          { id: '3', text: '좌석 배치 완료' },
          { id: '4', text: '신입생 교실 환경 점검' },
        ],
        tips: ['신입생 교실에 환영 게시물을 부착하면 좋습니다'],
        estimatedTime: 120,
      },
      {
        order: 5,
        title: '입학식 당일 진행',
        description: '입학식 당일 행사 진행',
        checkItems: [
          { id: '1', text: '안내 인력 배치' },
          { id: '2', text: '식순대로 진행' },
          { id: '3', text: '사진 촬영' },
          { id: '4', text: '교실 이동 안내' },
          { id: '5', text: '행사 후 정리' },
        ],
        estimatedTime: 180,
      },
    ],
  },
  {
    title: '교육과정 편성 및 시간표 작성',
    description: '학년별 교육과정 편성 및 주간 시간표 작성',
    categoryName: 'curriculum',
    month: 3,
    priority: 'URGENT',
    estimatedHours: 12,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['교무부장', '학년부장'],
    source: '전국 1000+ 학교 공통',
    tags: ['교육과정', '시간표', '학년초'],
    workflowSteps: [
      {
        order: 1,
        title: '교육과정 편성 기준 확인',
        description: '시도교육청 교육과정 편성 지침 확인',
        checkItems: [
          { id: '1', text: '국가수준 교육과정 확인' },
          { id: '2', text: '시도교육청 지침 확인' },
          { id: '3', text: '학교 교육과정 위원회 구성' },
        ],
        estimatedTime: 60,
      },
      {
        order: 2,
        title: '학년별 시수 배당',
        description: '교과별 연간 시수 배당',
        checkItems: [
          { id: '1', text: '교과별 기준 시수 확인' },
          { id: '2', text: '창의적 체험활동 시수 배당' },
          { id: '3', text: '자율시수 활용 계획' },
        ],
        estimatedTime: 90,
      },
      {
        order: 3,
        title: '시간표 작성',
        description: '주간 시간표 작성 및 조정',
        checkItems: [
          { id: '1', text: '전담교과 시간 배정' },
          { id: '2', text: '특별실 사용 시간 조정' },
          { id: '3', text: '학년별 시간표 완성' },
          { id: '4', text: '시간표 최종 검토' },
        ],
        tips: ['전담교사와 사전 협의가 필수입니다'],
        estimatedTime: 180,
      },
    ],
  },
  {
    title: '학부모 총회 준비 및 운영',
    description: '새 학년 학부모 총회 준비 및 진행',
    categoryName: 'parent_community',
    month: 3,
    priority: 'HIGH',
    estimatedHours: 8,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임', '학년부장'],
    source: '전국 1000+ 학교 공통',
    tags: ['학부모총회', '학년초', '학부모'],
  },
  {
    title: '학생건강검사 계획 수립',
    description: '연간 학생건강검사 계획 수립 및 일정 조정',
    categoryName: 'safety',
    month: 3,
    priority: 'MEDIUM',
    estimatedHours: 4,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['보건교사'],
    source: '학교건강검사규칙',
    tags: ['건강검사', '신체검사', '보건'],
  },

  // ===========================================
  // 4월 업무
  // ===========================================
  {
    title: '과학의 날 행사',
    description: '4월 과학의 날 기념 행사 운영',
    categoryName: 'school_events',
    month: 4,
    priority: 'MEDIUM',
    estimatedHours: 8,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['과학부장', '담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['과학의날', '체험행사', '과학'],
    workflowSteps: [
      {
        order: 1,
        title: '행사 기본 계획 수립',
        checkItems: [
          { id: '1', text: '행사 일정 확정' },
          { id: '2', text: '프로그램 구성' },
          { id: '3', text: '예산 확보' },
        ],
        estimatedTime: 60,
      },
      {
        order: 2,
        title: '체험부스 운영 계획',
        checkItems: [
          { id: '1', text: '학년별 체험활동 선정' },
          { id: '2', text: '준비물 목록 작성' },
          { id: '3', text: '부스 배치도 작성' },
        ],
        estimatedTime: 90,
      },
      {
        order: 3,
        title: '행사 당일 운영',
        checkItems: [
          { id: '1', text: '부스 설치' },
          { id: '2', text: '학년별 순환 진행' },
          { id: '3', text: '정리 및 뒷정리' },
        ],
        estimatedTime: 240,
      },
    ],
  },
  {
    title: '학교폭력 실태조사',
    description: '1차 학교폭력 실태조사 실시',
    categoryName: 'student_guidance',
    month: 4,
    priority: 'URGENT',
    estimatedHours: 6,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['생활부장', '담임'],
    source: '학교폭력예방법',
    tags: ['학교폭력', '실태조사', '안전'],
    workflowSteps: [
      {
        order: 1,
        title: '조사 준비',
        checkItems: [
          { id: '1', text: '조사 일정 공지' },
          { id: '2', text: '설문 시스템 접속 확인' },
          { id: '3', text: '학생 안내' },
        ],
        estimatedTime: 30,
      },
      {
        order: 2,
        title: '조사 실시',
        checkItems: [
          { id: '1', text: '컴퓨터실 이동 지도' },
          { id: '2', text: '조사 진행 모니터링' },
          { id: '3', text: '미참여 학생 확인' },
        ],
        estimatedTime: 60,
      },
      {
        order: 3,
        title: '결과 분석 및 조치',
        checkItems: [
          { id: '1', text: '조사 결과 확인' },
          { id: '2', text: '피해 학생 상담' },
          { id: '3', text: '학교폭력대책자치위원회 보고' },
        ],
        warnings: ['피해 신고 내용은 즉시 확인하고 조치해야 합니다'],
        estimatedTime: 120,
      },
    ],
  },
  {
    title: '학생건강검사 실시',
    description: '학년별 학생건강검사 실시',
    categoryName: 'safety',
    month: 4,
    priority: 'HIGH',
    estimatedHours: 16,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['보건교사', '담임'],
    source: '학교건강검사규칙',
    tags: ['건강검사', '신체검사', '보건'],
  },
  {
    title: '장애인의 날 계기교육',
    description: '장애인의 날(4.20) 계기 장애이해교육',
    categoryName: 'special_education',
    month: 4,
    priority: 'MEDIUM',
    estimatedHours: 2,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['특수교사', '담임'],
    source: '장애인복지법',
    tags: ['장애인의날', '장애이해', '인권'],
  },

  // ===========================================
  // 5월 업무
  // ===========================================
  {
    title: '어린이날 행사',
    description: '어린이날 기념 학교 행사 운영',
    categoryName: 'school_events',
    month: 5,
    priority: 'HIGH',
    estimatedHours: 8,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['체육부장', '담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['어린이날', '학교행사', '체험활동'],
  },
  {
    title: '학부모 상담주간 운영',
    description: '1학기 학부모 상담주간 운영',
    categoryName: 'parent_community',
    month: 5,
    priority: 'HIGH',
    estimatedHours: 10,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['학부모상담', '상담주간', '가정연계'],
    workflowSteps: [
      {
        order: 1,
        title: '상담주간 계획 안내',
        checkItems: [
          { id: '1', text: '상담 일정 안내문 발송' },
          { id: '2', text: '온라인 신청 시스템 오픈' },
          { id: '3', text: '상담 시간표 작성' },
        ],
        estimatedTime: 60,
      },
      {
        order: 2,
        title: '상담 자료 준비',
        checkItems: [
          { id: '1', text: '학생별 성적 자료 준비' },
          { id: '2', text: '생활 기록 정리' },
          { id: '3', text: '특이사항 메모' },
        ],
        tips: ['긍정적인 내용을 먼저 말씀드리면 좋습니다'],
        estimatedTime: 120,
      },
      {
        order: 3,
        title: '상담 진행',
        checkItems: [
          { id: '1', text: '상담 내용 기록' },
          { id: '2', text: '미상담 학부모 연락' },
          { id: '3', text: '상담 결과 NEIS 입력' },
        ],
        estimatedTime: 300,
      },
    ],
  },
  {
    title: '스승의 날 행사',
    description: '스승의 날 계기 감사 행사',
    categoryName: 'school_events',
    month: 5,
    priority: 'MEDIUM',
    estimatedHours: 4,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['교무부장'],
    source: '전국 1000+ 학교 공통',
    tags: ['스승의날', '감사행사'],
  },
  {
    title: '현장체험학습',
    description: '봄 현장체험학습 계획 및 실시',
    categoryName: 'school_events',
    month: 5,
    priority: 'HIGH',
    estimatedHours: 16,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['학년부장', '담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['현장체험학습', '소풍', '체험활동'],
    workflowSteps: [
      {
        order: 1,
        title: '현장체험학습 장소 선정',
        checkItems: [
          { id: '1', text: '학년별 장소 협의' },
          { id: '2', text: '안전점검표 확인' },
          { id: '3', text: '버스 견적 요청' },
          { id: '4', text: '최종 장소 확정' },
        ],
        tips: ['안전사고 발생 시 대응 가능한 장소인지 확인하세요'],
        estimatedTime: 120,
      },
      {
        order: 2,
        title: '계획서 작성 및 결재',
        checkItems: [
          { id: '1', text: '현장체험학습 계획서 작성' },
          { id: '2', text: '안전교육 계획 포함' },
          { id: '3', text: '관리자 결재' },
          { id: '4', text: '학부모 안내문 발송' },
        ],
        estimatedTime: 90,
      },
      {
        order: 3,
        title: '사전답사 및 준비',
        checkItems: [
          { id: '1', text: '사전답사 실시', isOptional: true },
          { id: '2', text: '비상연락망 작성' },
          { id: '3', text: '응급약품 준비' },
          { id: '4', text: '학생 조 편성' },
        ],
        estimatedTime: 120,
      },
      {
        order: 4,
        title: '당일 진행',
        checkItems: [
          { id: '1', text: '출발 전 인원 점검' },
          { id: '2', text: '차량 내 안전교육' },
          { id: '3', text: '활동 중 안전지도' },
          { id: '4', text: '귀교 후 인원 확인' },
        ],
        warnings: ['매 이동 시 인원을 반드시 확인하세요'],
        estimatedTime: 480,
      },
    ],
  },

  // ===========================================
  // 6월 업무
  // ===========================================
  {
    title: '현충일 계기교육',
    description: '현충일(6.6) 계기 나라사랑 교육',
    categoryName: 'academic_affairs',
    month: 6,
    priority: 'MEDIUM',
    estimatedHours: 2,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['현충일', '나라사랑', '계기교육'],
  },
  {
    title: '수영 안전교육',
    description: '여름철 수영 안전교육 실시',
    categoryName: 'safety',
    month: 6,
    priority: 'HIGH',
    estimatedHours: 4,
    targetGrades: [3, 4, 5, 6],
    targetPositions: ['체육교사', '담임'],
    source: '학교안전교육 7대 표준안',
    tags: ['수영', '안전교육', '여름'],
  },
  {
    title: '1학기 학업성적관리위원회',
    description: '1학기 성적 처리 전 학업성적관리위원회 개최',
    categoryName: 'academic_affairs',
    month: 6,
    priority: 'HIGH',
    estimatedHours: 4,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['교무부장', '학년부장'],
    source: '학업성적관리규정',
    tags: ['성적', '평가', '위원회'],
  },

  // ===========================================
  // 7월 업무
  // ===========================================
  {
    title: '1학기 성적 처리',
    description: 'NEIS를 통한 1학기 성적 입력 및 처리',
    categoryName: 'academic_affairs',
    month: 7,
    priority: 'URGENT',
    estimatedHours: 8,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임', '교과교사'],
    source: '학업성적관리규정',
    tags: ['성적', '평가', 'NEIS'],
    workflowSteps: [
      {
        order: 1,
        title: '성적 입력 준비',
        checkItems: [
          { id: '1', text: '성적 산출 기준 확인' },
          { id: '2', text: '수행평가 점수 정리' },
          { id: '3', text: '지필평가 점수 확인' },
        ],
        estimatedTime: 60,
      },
      {
        order: 2,
        title: 'NEIS 성적 입력',
        checkItems: [
          { id: '1', text: '교과별 성적 입력' },
          { id: '2', text: '성취도 확인' },
          { id: '3', text: '오입력 점검' },
        ],
        warnings: ['입력 기한을 반드시 지켜주세요'],
        estimatedTime: 120,
      },
      {
        order: 3,
        title: '성적 확인 및 마감',
        checkItems: [
          { id: '1', text: '학년부장 확인' },
          { id: '2', text: '교무부 확인' },
          { id: '3', text: '성적 마감' },
        ],
        estimatedTime: 60,
      },
    ],
  },
  {
    title: '생활통지표 작성',
    description: '1학기 생활통지표 작성 및 발송',
    categoryName: 'academic_affairs',
    month: 7,
    priority: 'URGENT',
    estimatedHours: 6,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['통지표', '성적', '가정통신'],
  },
  {
    title: '여름방학 계획 수립',
    description: '여름방학 중 학교 운영 계획 수립',
    categoryName: 'administrative',
    month: 7,
    priority: 'HIGH',
    estimatedHours: 4,
    targetGrades: [],
    targetPositions: ['교무부장', '행정실장'],
    source: '전국 1000+ 학교 공통',
    tags: ['방학', '계획', '운영'],
  },
  {
    title: '방학식',
    description: '1학기 종업식/방학식 행사',
    categoryName: 'school_events',
    month: 7,
    priority: 'HIGH',
    estimatedHours: 4,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['교무부장', '담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['방학식', '종업식', '학교행사'],
  },

  // ===========================================
  // 8월 업무
  // ===========================================
  {
    title: '2학기 교육과정 점검',
    description: '2학기 교육과정 운영 계획 점검 및 수정',
    categoryName: 'curriculum',
    month: 8,
    priority: 'HIGH',
    estimatedHours: 6,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['교무부장', '학년부장'],
    source: '전국 1000+ 학교 공통',
    tags: ['교육과정', '2학기', '계획'],
  },
  {
    title: '개학 준비',
    description: '2학기 개학 준비 업무',
    categoryName: 'administrative',
    month: 8,
    priority: 'URGENT',
    estimatedHours: 8,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임', '행정실'],
    source: '전국 1000+ 학교 공통',
    tags: ['개학', '2학기', '준비'],
  },
  {
    title: '개학식',
    description: '2학기 개학식/시업식 행사',
    categoryName: 'school_events',
    month: 8,
    priority: 'HIGH',
    estimatedHours: 2,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['교무부장', '담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['개학식', '시업식', '학교행사'],
  },

  // ===========================================
  // 9월 업무
  // ===========================================
  {
    title: '2차 학교폭력 실태조사',
    description: '2차 학교폭력 실태조사 실시',
    categoryName: 'student_guidance',
    month: 9,
    priority: 'URGENT',
    estimatedHours: 6,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['생활부장', '담임'],
    source: '학교폭력예방법',
    tags: ['학교폭력', '실태조사', '안전'],
  },
  {
    title: '추석 계기교육',
    description: '추석 계기 전통문화 교육',
    categoryName: 'academic_affairs',
    month: 9,
    priority: 'LOW',
    estimatedHours: 2,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['추석', '전통문화', '계기교육'],
  },

  // ===========================================
  // 10월 업무
  // ===========================================
  {
    title: '운동회/체육대회',
    description: '가을 운동회/체육대회 준비 및 진행',
    categoryName: 'school_events',
    month: 10,
    priority: 'HIGH',
    estimatedHours: 24,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['체육부장', '담임', '학년부장'],
    source: '전국 1000+ 학교 공통',
    tags: ['운동회', '체육대회', '학교행사'],
    workflowSteps: [
      {
        order: 1,
        title: '기본 계획 수립',
        checkItems: [
          { id: '1', text: '행사 일정 확정' },
          { id: '2', text: '종목 선정' },
          { id: '3', text: '예산 확보' },
          { id: '4', text: '역할 분담' },
        ],
        estimatedTime: 120,
      },
      {
        order: 2,
        title: '세부 계획',
        checkItems: [
          { id: '1', text: '학년별 종목 배정' },
          { id: '2', text: '시간표 작성' },
          { id: '3', text: '준비물 목록 작성' },
          { id: '4', text: '우천 시 계획' },
        ],
        estimatedTime: 180,
      },
      {
        order: 3,
        title: '사전 준비',
        checkItems: [
          { id: '1', text: '운동장 라인 작업' },
          { id: '2', text: '용품 준비' },
          { id: '3', text: '음향 시설 점검' },
          { id: '4', text: '천막 설치' },
        ],
        estimatedTime: 240,
      },
      {
        order: 4,
        title: '학생 연습',
        checkItems: [
          { id: '1', text: '개회식 연습' },
          { id: '2', text: '학년별 종목 연습' },
          { id: '3', text: '전체 리허설' },
        ],
        estimatedTime: 300,
      },
      {
        order: 5,
        title: '당일 운영',
        checkItems: [
          { id: '1', text: '아침 점검' },
          { id: '2', text: '학부모 안내' },
          { id: '3', text: '종목별 진행' },
          { id: '4', text: '시상식' },
          { id: '5', text: '정리' },
        ],
        estimatedTime: 480,
      },
    ],
  },
  {
    title: '한글날 계기교육',
    description: '한글날(10.9) 계기 한글사랑 교육',
    categoryName: 'academic_affairs',
    month: 10,
    priority: 'MEDIUM',
    estimatedHours: 2,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['한글날', '한글', '계기교육'],
  },
  {
    title: '가을 현장체험학습',
    description: '가을 현장체험학습 계획 및 실시',
    categoryName: 'school_events',
    month: 10,
    priority: 'HIGH',
    estimatedHours: 16,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['학년부장', '담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['현장체험학습', '가을소풍', '체험활동'],
  },

  // ===========================================
  // 11월 업무
  // ===========================================
  {
    title: '학예회/발표회',
    description: '학예회/학습발표회 준비 및 진행',
    categoryName: 'school_events',
    month: 11,
    priority: 'HIGH',
    estimatedHours: 20,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['문화예술부장', '담임', '학년부장'],
    source: '전국 1000+ 학교 공통',
    tags: ['학예회', '발표회', '학교행사'],
  },
  {
    title: '2학기 학부모 상담주간',
    description: '2학기 학부모 상담주간 운영',
    categoryName: 'parent_community',
    month: 11,
    priority: 'HIGH',
    estimatedHours: 10,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['학부모상담', '상담주간', '가정연계'],
  },
  {
    title: '2학기 학업성적관리위원회',
    description: '2학기 성적 처리 전 학업성적관리위원회 개최',
    categoryName: 'academic_affairs',
    month: 11,
    priority: 'HIGH',
    estimatedHours: 4,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['교무부장', '학년부장'],
    source: '학업성적관리규정',
    tags: ['성적', '평가', '위원회'],
  },

  // ===========================================
  // 12월 업무
  // ===========================================
  {
    title: '2학기 성적 처리',
    description: 'NEIS를 통한 2학기 성적 입력 및 처리',
    categoryName: 'academic_affairs',
    month: 12,
    priority: 'URGENT',
    estimatedHours: 8,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임', '교과교사'],
    source: '학업성적관리규정',
    tags: ['성적', '평가', 'NEIS'],
  },
  {
    title: '학교생활기록부 마감',
    description: '학년말 학교생활기록부 최종 마감',
    categoryName: 'academic_affairs',
    month: 12,
    priority: 'URGENT',
    estimatedHours: 12,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임'],
    source: '학교생활기록 작성 및 관리지침',
    tags: ['학생부', '생기부', '마감'],
    workflowSteps: [
      {
        order: 1,
        title: '입력 내용 점검',
        checkItems: [
          { id: '1', text: '인적사항 확인' },
          { id: '2', text: '출결상황 점검' },
          { id: '3', text: '수상경력 입력' },
          { id: '4', text: '창의적 체험활동 입력' },
        ],
        estimatedTime: 180,
      },
      {
        order: 2,
        title: '행동특성 및 종합의견 작성',
        checkItems: [
          { id: '1', text: '학생별 특성 정리' },
          { id: '2', text: '종합의견 작성' },
          { id: '3', text: '맞춤법 검사' },
          { id: '4', text: '객관적 사실 기록 확인' },
        ],
        tips: ['긍정적이고 구체적인 내용으로 작성하세요'],
        estimatedTime: 300,
      },
      {
        order: 3,
        title: '확인 및 마감',
        checkItems: [
          { id: '1', text: '담임 자가점검' },
          { id: '2', text: '학년부장 확인' },
          { id: '3', text: '교무부 확인' },
          { id: '4', text: '최종 마감' },
        ],
        warnings: ['마감 후에는 수정이 어려우니 신중히 점검하세요'],
        estimatedTime: 120,
      },
    ],
  },
  {
    title: '겨울방학 계획 수립',
    description: '겨울방학 중 학교 운영 계획 수립',
    categoryName: 'administrative',
    month: 12,
    priority: 'HIGH',
    estimatedHours: 4,
    targetGrades: [],
    targetPositions: ['교무부장', '행정실장'],
    source: '전국 1000+ 학교 공통',
    tags: ['방학', '계획', '운영'],
  },

  // ===========================================
  // 1월 업무
  // ===========================================
  {
    title: '졸업식 준비',
    description: '졸업식 행사 준비',
    categoryName: 'school_events',
    month: 1,
    priority: 'URGENT',
    estimatedHours: 16,
    targetGrades: [6],
    targetPositions: ['교무부장', '6학년부장', '담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['졸업식', '6학년', '학교행사'],
    workflowSteps: [
      {
        order: 1,
        title: '기본 계획 수립',
        checkItems: [
          { id: '1', text: '졸업식 일시 확정' },
          { id: '2', text: '행사 장소 확정' },
          { id: '3', text: '식순 작성' },
          { id: '4', text: '역할 분담표 작성' },
        ],
        estimatedTime: 60,
      },
      {
        order: 2,
        title: '졸업장 및 상장 준비',
        checkItems: [
          { id: '1', text: '졸업생 명단 최종 확인' },
          { id: '2', text: '졸업장 인쇄' },
          { id: '3', text: '상장 준비 (개근상, 공로상 등)' },
          { id: '4', text: '기념품 준비' },
        ],
        estimatedTime: 120,
      },
      {
        order: 3,
        title: '졸업식 준비물 점검',
        checkItems: [
          { id: '1', text: '현수막 제작' },
          { id: '2', text: '꽃바구니/화환 주문' },
          { id: '3', text: '음향/영상 장비 점검' },
          { id: '4', text: '졸업앨범 준비' },
        ],
        estimatedTime: 90,
      },
      {
        order: 4,
        title: '졸업식 리허설',
        checkItems: [
          { id: '1', text: '식순 연습' },
          { id: '2', text: '졸업생 입장 연습' },
          { id: '3', text: '송사/답사 연습' },
          { id: '4', text: '졸업장 수여 연습' },
        ],
        estimatedTime: 120,
      },
      {
        order: 5,
        title: '졸업식 당일',
        checkItems: [
          { id: '1', text: '행사장 최종 점검' },
          { id: '2', text: '안내 인력 배치' },
          { id: '3', text: '식순 진행' },
          { id: '4', text: '졸업장/상장 수여' },
          { id: '5', text: '기념 촬영' },
          { id: '6', text: '뒷정리' },
        ],
        estimatedTime: 240,
      },
    ],
  },
  {
    title: '졸업식 진행',
    description: '졸업식 행사 진행',
    categoryName: 'school_events',
    month: 1,
    priority: 'URGENT',
    estimatedHours: 8,
    targetGrades: [6],
    targetPositions: ['교무부장', '6학년담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['졸업식', '6학년', '학교행사'],
  },
  {
    title: '종업식',
    description: '학년말 종업식 행사',
    categoryName: 'school_events',
    month: 1,
    priority: 'HIGH',
    estimatedHours: 4,
    targetGrades: [1, 2, 3, 4, 5],
    targetPositions: ['교무부장', '담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['종업식', '학년말', '학교행사'],
  },

  // ===========================================
  // 2월 업무
  // ===========================================
  {
    title: '신학년도 업무 분장',
    description: '다음 학년도 교직원 업무 분장 계획',
    categoryName: 'administrative',
    month: 2,
    priority: 'URGENT',
    estimatedHours: 8,
    targetGrades: [],
    targetPositions: ['교감', '교무부장'],
    source: '전국 1000+ 학교 공통',
    tags: ['업무분장', '인사', '학년초준비'],
  },
  {
    title: '신학년도 교육과정 편성',
    description: '다음 학년도 교육과정 편성 계획',
    categoryName: 'curriculum',
    month: 2,
    priority: 'URGENT',
    estimatedHours: 12,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['교무부장', '학년부장'],
    source: '전국 1000+ 학교 공통',
    tags: ['교육과정', '신학년', '계획'],
  },
  {
    title: '신입생 예비소집',
    description: '신입생 예비소집 및 반편성 배치고사',
    categoryName: 'academic_affairs',
    month: 2,
    priority: 'HIGH',
    estimatedHours: 6,
    targetGrades: [1],
    targetPositions: ['교무부장', '1학년부장'],
    source: '전국 1000+ 학교 공통',
    tags: ['신입생', '예비소집', '입학'],
  },
  {
    title: '교실 환경 정비',
    description: '신학년도 대비 교실 환경 정비',
    categoryName: 'facilities',
    month: 2,
    priority: 'MEDIUM',
    estimatedHours: 8,
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임', '시설관리'],
    source: '전국 1000+ 학교 공통',
    tags: ['교실', '환경정비', '신학년'],
  },

  // ===========================================
  // 연중 상시 업무
  // ===========================================
  {
    title: '생활지도',
    description: '일상적인 학생 생활지도',
    categoryName: 'student_guidance',
    isRecurring: true,
    recurringType: 'DAILY',
    priority: 'HIGH',
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['생활지도', '상시업무'],
  },
  {
    title: '출결관리',
    description: 'NEIS를 통한 일일 출결 관리',
    categoryName: 'academic_affairs',
    isRecurring: true,
    recurringType: 'DAILY',
    priority: 'HIGH',
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임'],
    source: '학교생활기록 작성 및 관리지침',
    tags: ['출결', 'NEIS', '상시업무'],
  },
  {
    title: '학교홈페이지 관리',
    description: '학교 홈페이지 게시물 관리 및 업데이트',
    categoryName: 'ict',
    isRecurring: true,
    recurringType: 'WEEKLY',
    priority: 'MEDIUM',
    targetGrades: [],
    targetPositions: ['정보부장', '담당교사'],
    source: '전국 1000+ 학교 공통',
    tags: ['홈페이지', '정보화', '상시업무'],
  },
  {
    title: '급식 지도',
    description: '점심시간 급식 지도',
    categoryName: 'school_meals',
    isRecurring: true,
    recurringType: 'DAILY',
    priority: 'MEDIUM',
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['담임'],
    source: '전국 1000+ 학교 공통',
    tags: ['급식', '생활지도', '상시업무'],
  },
  {
    title: '방과후학교 운영',
    description: '방과후학교 프로그램 운영 관리',
    categoryName: 'after_school',
    isRecurring: true,
    recurringType: 'WEEKLY',
    priority: 'MEDIUM',
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['방과후부장'],
    source: '전국 1000+ 학교 공통',
    tags: ['방과후', '돌봄', '상시업무'],
  },
  {
    title: '안전점검의 날',
    description: '매월 4일 안전점검의 날 실시',
    categoryName: 'safety',
    isRecurring: true,
    recurringType: 'MONTHLY',
    priority: 'HIGH',
    targetGrades: [1, 2, 3, 4, 5, 6],
    targetPositions: ['안전부장', '담임'],
    source: '학교안전관리법',
    tags: ['안전점검', '안전교육', '상시업무'],
  },
];

export type { TaskSeed, WorkflowStepSeed };
