'use client';

// v2.0 - localStorage 기반 + 기본 업무 자동 생성

import { useState, useMemo, useEffect, useCallback } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Progress } from '@/components/ui/progress';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import {
  CheckCircle2,
  Circle,
  Clock,
  AlertCircle,
  Plus,
  Search,
  Calendar,
  Trash2,
  Edit,
  Star,
  Sparkles,
  RefreshCw,
  Download,
} from 'lucide-react';
import { getTasksForDuties, getTasksForMonth, type BasicTask } from '@/data/homeroom-teacher-basic-tasks';
import { useUserSettings } from '@/hooks/useFirestore';

// 로컬 Task 타입
interface LocalTask {
  id: string;
  title: string;
  description: string;
  category: string;
  priority: 'high' | 'medium' | 'low';
  status: 'pending' | 'in_progress' | 'completed';
  progress: number;
  dueDate: string | null;
  createdAt: string;
  updatedAt: string;
  isAutoGenerated?: boolean;
}

const priorityConfig = {
  high: { label: '긴급', color: 'bg-red-500', textColor: 'text-red-700', bgColor: 'bg-red-50' },
  medium: { label: '보통', color: 'bg-yellow-500', textColor: 'text-yellow-700', bgColor: 'bg-yellow-50' },
  low: { label: '낮음', color: 'bg-green-500', textColor: 'text-green-700', bgColor: 'bg-green-50' },
};

const statusConfig = {
  pending: { label: '대기중', icon: Circle, color: 'text-gray-500' },
  in_progress: { label: '진행중', icon: Clock, color: 'text-blue-500' },
  completed: { label: '완료', icon: CheckCircle2, color: 'text-green-500' },
};

const categories = ['전체', '학급경영', '학부모', '체험학습', '안전', '교육과정', '방과후', '생활기록', '행사', '정보', '기타'];

// localStorage 키
const TASKS_STORAGE_KEY = 'eduflow_tasks';
const GENERATED_TASKS_KEY = 'eduflow_generated_tasks_version';

export default function TasksPage() {
  const { settings: userSettings, loading: settingsLoading } = useUserSettings();
  const [tasks, setTasks] = useState<LocalTask[]>([]);
  const [userDuties, setUserDuties] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('전체');
  const [selectedStatus, setSelectedStatus] = useState<string | null>(null);
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
  const [editingTask, setEditingTask] = useState<LocalTask | null>(null);

  // New task form state
  const [newTask, setNewTask] = useState({
    title: '',
    description: '',
    category: '학급경영',
    priority: 'medium' as 'high' | 'medium' | 'low',
    status: 'pending' as 'pending' | 'in_progress' | 'completed',
    dueDate: '',
    progress: 0,
  });

  // 사용자 설정에서 업무 가져오기 (Firebase에서 저장된 설정)
  useEffect(() => {
    if (userSettings) {
      const roles = userSettings.roles || [];
      const customTasks = (userSettings as any).customTasks || [];
      const allDuties = [...roles, ...customTasks];
      if (allDuties.length > 0) {
        setUserDuties(allDuties);
        // Also sync to localStorage for backward compatibility
        localStorage.setItem('eduflow_user_duties', JSON.stringify(allDuties));
      }
    }
  }, [userSettings]);

  // localStorage에서 tasks 로드
  useEffect(() => {
    const loadTasks = () => {
      try {
        const saved = localStorage.getItem(TASKS_STORAGE_KEY);
        if (saved) {
          setTasks(JSON.parse(saved));
        }
      } catch (e) {
        console.error('[Tasks] 업무 로드 실패:', e);
      } finally {
        setLoading(false);
      }
    };

    // Wait for settings to load before loading tasks
    if (!settingsLoading) {
      loadTasks();
    }
  }, [settingsLoading]);

  // tasks 저장
  const saveTasks = useCallback((newTasks: LocalTask[]) => {
    setTasks(newTasks);
    localStorage.setItem(TASKS_STORAGE_KEY, JSON.stringify(newTasks));
  }, []);

  // BasicTask를 LocalTask로 변환
  const convertBasicToLocalTask = (basicTask: BasicTask): LocalTask => {
    const now = new Date().toISOString();
    let dueDate: string | null = null;

    if (basicTask.dueDate) {
      const [month, day] = basicTask.dueDate.split('-').map(Number);
      const year = new Date().getFullYear();
      const date = new Date(year, month - 1, day);
      // 만약 이미 지났으면 다음 해로
      if (date < new Date()) {
        date.setFullYear(year + 1);
      }
      dueDate = date.toISOString().split('T')[0];
    } else if (basicTask.month) {
      // 해당 월의 마지막 날로 설정
      const year = new Date().getFullYear();
      const month = basicTask.month;
      const lastDay = new Date(year, month, 0).getDate();
      const date = new Date(year, month - 1, lastDay);
      if (date < new Date()) {
        date.setFullYear(year + 1);
      }
      dueDate = date.toISOString().split('T')[0];
    }

    return {
      id: `auto_${basicTask.id}_${Date.now()}`,
      title: basicTask.title,
      description: basicTask.description,
      category: basicTask.category,
      priority: basicTask.priority,
      status: 'pending',
      progress: 0,
      dueDate,
      createdAt: now,
      updatedAt: now,
      isAutoGenerated: true,
    };
  };

  // 현재 월 업무 자동 생성
  const generateMonthlyTasks = useCallback(() => {
    const currentMonth = new Date().getMonth() + 1;
    const versionKey = `${currentMonth}_${new Date().getFullYear()}`;
    const lastVersion = localStorage.getItem(GENERATED_TASKS_KEY);

    // 이미 이번 달 업무를 생성했으면 스킵
    if (lastVersion === versionKey && tasks.length > 0) {
      return;
    }

    // 사용자 업무에 맞는 업무 가져오기
    let basicTasks: BasicTask[] = [];
    if (userDuties.length > 0) {
      basicTasks = getTasksForDuties(userDuties).filter(
        task => !task.month || task.month === currentMonth ||
        task.frequency === 'daily' || task.frequency === 'weekly' || task.frequency === 'monthly'
      );
    } else {
      // 업무 설정이 없으면 이번 달 공통 업무만
      basicTasks = getTasksForMonth(currentMonth);
    }

    // 중복 제거 (이미 있는 업무는 추가하지 않음)
    const existingTitles = new Set(tasks.map(t => t.title));
    const newBasicTasks = basicTasks.filter(bt => !existingTitles.has(bt.title));

    if (newBasicTasks.length > 0) {
      const newLocalTasks = newBasicTasks.map(convertBasicToLocalTask);
      const updatedTasks = [...tasks, ...newLocalTasks];
      saveTasks(updatedTasks);
      localStorage.setItem(GENERATED_TASKS_KEY, versionKey);
    }
  }, [userDuties, tasks, saveTasks]);

  // 초기 업무 생성 (설정된 업무가 있고, 업무 목록이 비어있을 때)
  useEffect(() => {
    if (!loading && tasks.length === 0 && userDuties.length > 0) {
      generateMonthlyTasks();
    }
  }, [loading, tasks.length, userDuties.length, generateMonthlyTasks]);

  // 수동 업무 새로고침
  const handleRefreshTasks = () => {
    if (confirm('이번 달 기본 업무를 추가하시겠습니까? 기존 업무는 유지됩니다.')) {
      localStorage.removeItem(GENERATED_TASKS_KEY);
      generateMonthlyTasks();
    }
  };

  // 사용자 업무에 맞는 카테고리
  const matchedCategories = useMemo(() => {
    const cats = new Set<string>();
    tasks.forEach(task => {
      if (task.isAutoGenerated) {
        cats.add(task.category);
      }
    });
    return Array.from(cats);
  }, [tasks]);

  // 필터링 및 정렬
  const filteredTasks = useMemo(() => {
    let result = tasks.filter((task) => {
      const matchesSearch = task.title.toLowerCase().includes(searchQuery.toLowerCase());
      const matchesCategory = selectedCategory === '전체' || task.category === selectedCategory;
      const matchesStatus = !selectedStatus || task.status === selectedStatus;
      return matchesSearch && matchesCategory && matchesStatus;
    });

    // 마감일 순으로 정렬 (가까운 순), 완료된 건 마지막
    result = [...result].sort((a, b) => {
      if (a.status === 'completed' && b.status !== 'completed') return 1;
      if (a.status !== 'completed' && b.status === 'completed') return -1;

      if (a.dueDate && b.dueDate) {
        return new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime();
      }
      if (a.dueDate) return -1;
      if (b.dueDate) return 1;

      // 우선순위 정렬
      const priorityOrder = { high: 0, medium: 1, low: 2 };
      return priorityOrder[a.priority] - priorityOrder[b.priority];
    });

    return result;
  }, [tasks, searchQuery, selectedCategory, selectedStatus]);

  const taskStats = {
    total: tasks.length,
    pending: tasks.filter((t) => t.status === 'pending').length,
    inProgress: tasks.filter((t) => t.status === 'in_progress').length,
    completed: tasks.filter((t) => t.status === 'completed').length,
  };

  // 업무 추가
  const handleAddTask = () => {
    if (!newTask.title.trim()) return;

    const now = new Date().toISOString();
    const task: LocalTask = {
      id: `task_${Date.now()}`,
      ...newTask,
      dueDate: newTask.dueDate || null,
      createdAt: now,
      updatedAt: now,
    };

    saveTasks([...tasks, task]);
    setNewTask({
      title: '',
      description: '',
      category: '학급경영',
      priority: 'medium',
      status: 'pending',
      dueDate: '',
      progress: 0,
    });
    setIsAddDialogOpen(false);
  };

  // 업무 수정
  const handleEditTask = () => {
    if (!editingTask) return;

    const updatedTasks = tasks.map((t) =>
      t.id === editingTask.id
        ? { ...editingTask, updatedAt: new Date().toISOString() }
        : t
    );
    saveTasks(updatedTasks);
    setIsEditDialogOpen(false);
    setEditingTask(null);
  };

  // 업무 삭제
  const handleDeleteTask = (taskId: string) => {
    if (confirm('정말로 이 업무를 삭제하시겠습니까?')) {
      saveTasks(tasks.filter((t) => t.id !== taskId));
    }
  };

  // 상태 빠른 변경
  const handleQuickStatusChange = (taskId: string, newStatus: LocalTask['status']) => {
    const updatedTasks = tasks.map((t) =>
      t.id === taskId
        ? {
            ...t,
            status: newStatus,
            progress: newStatus === 'completed' ? 100 : newStatus === 'in_progress' ? 50 : 0,
            updatedAt: new Date().toISOString(),
          }
        : t
    );
    saveTasks(updatedTasks);
  };

  const openEditDialog = (task: LocalTask) => {
    setEditingTask({ ...task });
    setIsEditDialogOpen(true);
  };

  const formatDueDate = (dueDate: string | null): string => {
    if (!dueDate) return '미정';
    return new Date(dueDate).toLocaleDateString('ko-KR');
  };

  const getDueDateColor = (dueDate: string | null, status: string): string => {
    if (!dueDate || status === 'completed') return '';
    const today = new Date();
    const due = new Date(dueDate);
    const diffDays = Math.ceil((due.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));

    if (diffDays < 0) return 'text-red-600 font-semibold'; // 지남
    if (diffDays <= 3) return 'text-orange-600'; // 3일 이내
    if (diffDays <= 7) return 'text-yellow-600'; // 1주일 이내
    return '';
  };

  if (loading || settingsLoading) {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div className="space-y-2 animate-pulse">
            <div className="h-8 w-32 bg-muted rounded" />
            <div className="h-4 w-48 bg-muted rounded" />
          </div>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
          {[1, 2, 3, 4].map((i) => (
            <div key={i} className="h-20 bg-muted rounded-lg animate-pulse" />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div>
          <h1 className="text-2xl font-bold">업무 관리</h1>
          <p className="text-muted-foreground">
            총 {taskStats.total}개의 업무 중 {taskStats.completed}개 완료
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" onClick={handleRefreshTasks}>
            <RefreshCw className="h-4 w-4 mr-2" />
            이번 달 업무 추가
          </Button>
          <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
            <DialogTrigger asChild>
              <Button>
                <Plus className="h-4 w-4 mr-2" />
                새 업무 추가
              </Button>
            </DialogTrigger>
            <DialogContent className="sm:max-w-[500px]">
              <DialogHeader>
                <DialogTitle>새 업무 추가</DialogTitle>
                <DialogDescription>
                  새로운 업무를 추가합니다.
                </DialogDescription>
              </DialogHeader>
              <div className="grid gap-4 py-4">
                <div className="grid gap-2">
                  <Label htmlFor="title">업무명 *</Label>
                  <Input
                    id="title"
                    value={newTask.title}
                    onChange={(e) => setNewTask({ ...newTask, title: e.target.value })}
                    placeholder="업무명을 입력하세요"
                  />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="description">설명</Label>
                  <Textarea
                    id="description"
                    value={newTask.description}
                    onChange={(e) => setNewTask({ ...newTask, description: e.target.value })}
                    placeholder="업무에 대한 설명을 입력하세요"
                  />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="grid gap-2">
                    <Label>카테고리</Label>
                    <Select
                      value={newTask.category}
                      onValueChange={(value) => setNewTask({ ...newTask, category: value })}
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {categories.filter((c) => c !== '전체').map((cat) => (
                          <SelectItem key={cat} value={cat}>{cat}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="grid gap-2">
                    <Label>우선순위</Label>
                    <Select
                      value={newTask.priority}
                      onValueChange={(value: 'high' | 'medium' | 'low') =>
                        setNewTask({ ...newTask, priority: value })
                      }
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="high">긴급</SelectItem>
                        <SelectItem value="medium">보통</SelectItem>
                        <SelectItem value="low">낮음</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="dueDate">마감일</Label>
                  <Input
                    id="dueDate"
                    type="date"
                    value={newTask.dueDate}
                    onChange={(e) => setNewTask({ ...newTask, dueDate: e.target.value })}
                  />
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setIsAddDialogOpen(false)}>
                  취소
                </Button>
                <Button onClick={handleAddTask} disabled={!newTask.title.trim()}>
                  추가
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card
          className={`cursor-pointer transition-colors ${!selectedStatus ? 'ring-2 ring-primary' : ''}`}
          onClick={() => setSelectedStatus(null)}
        >
          <CardContent className="pt-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">전체 업무</p>
                <p className="text-2xl font-bold">{taskStats.total}</p>
              </div>
              <div className="p-3 rounded-full bg-primary/10">
                <CheckCircle2 className="h-6 w-6 text-primary" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card
          className={`cursor-pointer transition-colors ${selectedStatus === 'pending' ? 'ring-2 ring-gray-500' : ''}`}
          onClick={() => setSelectedStatus(selectedStatus === 'pending' ? null : 'pending')}
        >
          <CardContent className="pt-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">대기중</p>
                <p className="text-2xl font-bold">{taskStats.pending}</p>
              </div>
              <div className="p-3 rounded-full bg-gray-100">
                <Circle className="h-6 w-6 text-gray-500" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card
          className={`cursor-pointer transition-colors ${selectedStatus === 'in_progress' ? 'ring-2 ring-blue-500' : ''}`}
          onClick={() => setSelectedStatus(selectedStatus === 'in_progress' ? null : 'in_progress')}
        >
          <CardContent className="pt-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">진행중</p>
                <p className="text-2xl font-bold">{taskStats.inProgress}</p>
              </div>
              <div className="p-3 rounded-full bg-blue-100">
                <Clock className="h-6 w-6 text-blue-500" />
              </div>
            </div>
          </CardContent>
        </Card>

        <Card
          className={`cursor-pointer transition-colors ${selectedStatus === 'completed' ? 'ring-2 ring-green-500' : ''}`}
          onClick={() => setSelectedStatus(selectedStatus === 'completed' ? null : 'completed')}
        >
          <CardContent className="pt-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-muted-foreground">완료</p>
                <p className="text-2xl font-bold">{taskStats.completed}</p>
              </div>
              <div className="p-3 rounded-full bg-green-100">
                <CheckCircle2 className="h-6 w-6 text-green-500" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* 업무 설정 안내 */}
      {tasks.length === 0 && (
        <Card className="border-dashed">
          <CardContent className="pt-6">
            <div className="flex flex-col items-center text-center gap-4">
              <div className="p-4 rounded-full bg-primary/10">
                <Download className="h-8 w-8 text-primary" />
              </div>
              <div>
                <h3 className="font-semibold text-lg mb-1">업무 목록이 비어있습니다</h3>
                <p className="text-muted-foreground text-sm mb-4">
                  설정에서 업무분장을 선택하면, 해당 업무에 맞는 기본 업무가 자동으로 추가됩니다.
                  <br />
                  또는 '이번 달 업무 추가' 버튼을 클릭하여 이번 달 담임 기본 업무를 추가할 수 있습니다.
                </p>
                <div className="flex gap-2 justify-center">
                  <Button variant="outline" asChild>
                    <a href="/settings">설정에서 업무 선택</a>
                  </Button>
                  <Button onClick={handleRefreshTasks}>
                    이번 달 기본 업무 추가
                  </Button>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* 나의 업무 카테고리 */}
      {matchedCategories.length > 0 && (
        <Card className="border-primary/30 bg-gradient-to-r from-primary/5 to-primary/10">
          <CardContent className="pt-4">
            <div className="flex items-start gap-4">
              <div className="p-2 rounded-lg bg-primary/20">
                <Sparkles className="h-5 w-5 text-primary" />
              </div>
              <div className="flex-1">
                <h3 className="font-semibold text-primary mb-1">자동 생성된 업무 카테고리</h3>
                <p className="text-sm text-muted-foreground mb-2">
                  설정에서 선택한 업무를 기반으로 이번 달 업무가 자동 추가되었습니다.
                </p>
                <div className="flex flex-wrap gap-2">
                  {matchedCategories.map((cat) => (
                    <Badge
                      key={cat}
                      variant="secondary"
                      className="bg-primary/20 text-primary cursor-pointer hover:bg-primary/30"
                      onClick={() => setSelectedCategory(cat)}
                    >
                      <Star className="h-3 w-3 mr-1 fill-primary" />
                      {cat}
                    </Badge>
                  ))}
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Filters */}
      {tasks.length > 0 && (
        <Card>
          <CardContent className="pt-4">
            <div className="flex flex-col md:flex-row gap-4">
              <div className="relative flex-1">
                <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="업무 검색..."
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="pl-10"
                />
              </div>
              <div className="flex gap-2 overflow-x-auto pb-2 md:pb-0">
                {categories.map((category) => (
                  <Button
                    key={category}
                    variant={selectedCategory === category ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => setSelectedCategory(category)}
                    className="whitespace-nowrap"
                  >
                    {category}
                  </Button>
                ))}
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Task List */}
      {tasks.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center justify-between">
              <span>업무 목록</span>
              <Badge variant="secondary">{filteredTasks.length}개</Badge>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ScrollArea className="h-[500px]">
              <div className="space-y-3">
                {filteredTasks.map((task) => {
                  const StatusIcon = statusConfig[task.status].icon;
                  const priority = priorityConfig[task.priority];
                  const dueDateColor = getDueDateColor(task.dueDate, task.status);

                  return (
                    <div
                      key={task.id}
                      className={`p-4 border rounded-lg hover:bg-accent/50 transition-colors ${
                        task.status === 'completed' ? 'opacity-60' : ''
                      }`}
                    >
                      <div className="flex items-start gap-4">
                        {/* 상태 아이콘 - 클릭으로 상태 변경 */}
                        <button
                          className={`mt-1 ${statusConfig[task.status].color} hover:scale-110 transition-transform`}
                          onClick={() => {
                            const nextStatus: Record<LocalTask['status'], LocalTask['status']> = {
                              pending: 'in_progress',
                              in_progress: 'completed',
                              completed: 'pending',
                            };
                            handleQuickStatusChange(task.id, nextStatus[task.status]);
                          }}
                          title="클릭하여 상태 변경"
                        >
                          <StatusIcon className="h-5 w-5" />
                        </button>

                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 mb-1 flex-wrap">
                            {task.isAutoGenerated && (
                              <Badge variant="secondary" className="text-xs px-1.5 py-0 bg-blue-50 text-blue-700">
                                자동
                              </Badge>
                            )}
                            <h3 className={`font-medium ${task.status === 'completed' ? 'line-through' : ''}`}>
                              {task.title}
                            </h3>
                          </div>
                          <p className="text-sm text-muted-foreground truncate mb-2">
                            {task.description}
                          </p>
                          <div className="flex items-center gap-3 text-xs flex-wrap">
                            <Badge variant="secondary">{task.category}</Badge>
                            <span className={`px-2 py-0.5 rounded-full ${priority.bgColor} ${priority.textColor}`}>
                              {priority.label}
                            </span>
                            <span className={`flex items-center ${dueDateColor || 'text-muted-foreground'}`}>
                              <Calendar className="h-3 w-3 mr-1" />
                              {formatDueDate(task.dueDate)}
                            </span>
                          </div>
                          {task.status === 'in_progress' && (
                            <div className="mt-3">
                              <div className="flex items-center justify-between text-xs mb-1">
                                <span className="text-muted-foreground">진행률</span>
                                <span className="font-medium">{task.progress}%</span>
                              </div>
                              <Progress value={task.progress} className="h-1.5" />
                            </div>
                          )}
                        </div>

                        <div className="flex items-center gap-1">
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={() => openEditDialog(task)}
                          >
                            <Edit className="h-4 w-4" />
                          </Button>
                          <Button
                            variant="ghost"
                            size="icon"
                            onClick={() => handleDeleteTask(task.id)}
                            className="text-destructive hover:text-destructive"
                          >
                            <Trash2 className="h-4 w-4" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  );
                })}

                {filteredTasks.length === 0 && tasks.length > 0 && (
                  <div className="text-center py-12 text-muted-foreground">
                    <AlertCircle className="h-12 w-12 mx-auto mb-4 opacity-50" />
                    <p>검색 결과가 없습니다.</p>
                  </div>
                )}
              </div>
            </ScrollArea>
          </CardContent>
        </Card>
      )}

      {/* Edit Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent className="sm:max-w-[500px]">
          <DialogHeader>
            <DialogTitle>업무 수정</DialogTitle>
            <DialogDescription>
              업무 정보를 수정합니다.
            </DialogDescription>
          </DialogHeader>
          {editingTask && (
            <div className="grid gap-4 py-4">
              <div className="grid gap-2">
                <Label htmlFor="edit-title">업무명 *</Label>
                <Input
                  id="edit-title"
                  value={editingTask.title}
                  onChange={(e) => setEditingTask({ ...editingTask, title: e.target.value })}
                />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="edit-description">설명</Label>
                <Textarea
                  id="edit-description"
                  value={editingTask.description}
                  onChange={(e) => setEditingTask({ ...editingTask, description: e.target.value })}
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="grid gap-2">
                  <Label>카테고리</Label>
                  <Select
                    value={editingTask.category}
                    onValueChange={(value) => setEditingTask({ ...editingTask, category: value })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {categories.filter((c) => c !== '전체').map((cat) => (
                        <SelectItem key={cat} value={cat}>{cat}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="grid gap-2">
                  <Label>우선순위</Label>
                  <Select
                    value={editingTask.priority}
                    onValueChange={(value: 'high' | 'medium' | 'low') =>
                      setEditingTask({ ...editingTask, priority: value })
                    }
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="high">긴급</SelectItem>
                      <SelectItem value="medium">보통</SelectItem>
                      <SelectItem value="low">낮음</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="grid gap-2">
                  <Label>상태</Label>
                  <Select
                    value={editingTask.status}
                    onValueChange={(value: 'pending' | 'in_progress' | 'completed') =>
                      setEditingTask({
                        ...editingTask,
                        status: value,
                        progress: value === 'completed' ? 100 : value === 'in_progress' ? editingTask.progress : 0,
                      })
                    }
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="pending">대기중</SelectItem>
                      <SelectItem value="in_progress">진행중</SelectItem>
                      <SelectItem value="completed">완료</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="grid gap-2">
                  <Label>진행률 ({editingTask.progress}%)</Label>
                  <Input
                    type="range"
                    min="0"
                    max="100"
                    value={editingTask.progress}
                    onChange={(e) => setEditingTask({ ...editingTask, progress: parseInt(e.target.value) })}
                  />
                </div>
              </div>
              <div className="grid gap-2">
                <Label htmlFor="edit-dueDate">마감일</Label>
                <Input
                  id="edit-dueDate"
                  type="date"
                  value={editingTask.dueDate || ''}
                  onChange={(e) => setEditingTask({ ...editingTask, dueDate: e.target.value || null })}
                />
              </div>
            </div>
          )}
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsEditDialogOpen(false)}>
              취소
            </Button>
            <Button onClick={handleEditTask}>
              저장
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
